version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to your backend Dockerfile
    container_name: backend
    ports:
      - "8080:8080"  # Expose backend on port 8080
    networks:
      - mlops-network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend_mlops  # Path to your frontend Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    networks:
      - mlops-network
    depends_on:
      - backend  # Ensure the backend is up before frontend

networks:
  mlops-network:
    driver: bridge
