version: '3.8'

services:
  backend-service:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - mlops-network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend_mlops
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mlops-network
    depends_on:
      - backend-service

networks:
  mlops-network:
    driver: bridge
