version: '3.8'

services:
  backend-service:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - mlops-network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend_mlops
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mlops-network
    depends_on:
      - backend-service

  bentoml-service:
    build:
      context: ./lora  # Replace with the correct path
    container_name: bentoml-service
    ports:
      - "3002:3002"  # Port where Bentoml will be accessible
    networks:
      - mlops-network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  mlops-network:
    driver: bridge
