apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/frontend-image:latest # TODO replace with repo address
        ports:
        - containerPort: 3000

